language: python
python:
  - 2.7
env:
  - TOXENV=django18
  - TOXENV=django111
matrix:
  include:
    - python: 2.7
      env: TOXENV=quality
before_install:
  - export DJANGO_SETTINGS_MODULE=settings
install:
  - "make install"
sudo: false
script:
  - make test
branches:
    only:
      - master
after_success: coveralls
