language: python


python:
  - "2.7"


before_install:
  - export DJANGO_SETTINGS_MODULE=settings


# command to install dependencies
install:
    - "pip install coveralls"
    - "pip install pep8"
    - "pip install pylint"
    - "pip install -r requirements.txt"
    - "pip install -r test_requirements.txt"


# command to run tests and quality checks
script:
    - coverage run ./manage.py test
    - coverage report -m
    - pep8 --config=.pep8 milestones
    - pylint --rcfile=.pylintrc milestones


after_success: coveralls
