language: python
python: "2.7"
before_install:
  - export DJANGO_SETTINGS_MODULE=settings
install:
  - "make install"
sudo: false
script:
  - make quality
  - make test
branches:
    only:
      - master
after_success: coveralls
